name: Build Docker Container

on:
  push:
    branches: [main]
    tags: ['*']

env:
  REGISTRY: ghcr.io
  # Hardcoded name change
  IMAGE_NAME: ${{ github.repository_owner }}/say_hello

jobs:
  build-docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract SCM version
        id: scm
        run: |
          RAW_VERSION=$(pipx run hatch version)
          echo "version=$(echo $RAW_VERSION | tr '+' '-')" >> $GITHUB_OUTPUT

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,format=short
            type=raw,value=${{ steps.scm.outputs.version }}

      - name: Log in and Build
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: containers/say_hello.Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
