name: Build Apptainer Container

on:
  push:
    branches: [main]
    tags: ['*']

env:
  REGISTRY: ghcr.io
  # Hardcoded name change
  IMAGE_NAME: ${{ github.repository_owner }}/say_hello-sif

jobs:
  build-apptainer:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract SCM version
        id: scm
        run: |
          RAW_VERSION=$(pipx run hatch version)
          echo "version=$(echo $RAW_VERSION | tr '+' '-')" >> $GITHUB_OUTPUT

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,format=short
            type=raw,value=${{ steps.scm.outputs.version }}

      - name: Setup Apptainer
        uses: eWaterCycle/setup-apptainer@v2
        with:
          apptainer-version: 1.3.1

      - name: Build and Push
        run: |
          sudo apptainer build say_hello.sif containers/say_hello.def
          echo "${{ secrets.GITHUB_TOKEN }}" | apptainer remote login -u ${{ github.actor }} --password-stdin oras://${{ env.REGISTRY }}
          
          for TAG in ${{ steps.meta.outputs.tags }}; do
            apptainer push say_hello.sif oras://${TAG}
          done
